---

- name: Install supervisord into NGI venv
  shell: conda install -n {{ NGI_venv_name }} supervisor

- name: Create ngi_resources folder
  file:
    name: "{{ ngi_resources }}"
    state: directory

- name: Deploy crontab file for {{ site }}
  template:
    src: crontab.j2
    dest: "{{ ngi_pipeline_conf }}/crontab_{{ site }}"

- name: Deploy supervisord.conf for {{ site }}
  template:
    src: supervisord_site.conf.j2
    dest: "{{ supervisord_conf }}"

- name: Deploy start supervisord start script for {{ site }}
  template:
    src: start_supervisord_site.sh.j2
    dest: "{{ ngi_resources }}/start_supervisord_{{ site }}.sh"

- name: add static folders to be created
  set_fact:
    static_folders: "{{ static_folders + [supervisord_log_dest] }}"

- name: add static commands to be run
  set_fact:
    static_commands: "{{ static_commands + ['crontab ' ~ ngi_pipeline_conf ~ '/crontab_' ~ site] }}"
