# NOTE: This file is run in seqreports role as well!

- name: clone checkqc repository
  git:
    repo: "{{ checkqc_repo }}"
    version: "v{{ checkqc_version }}"
    depth: 1
    dest: /tmp/checkQC

- name: fix miarka_deployment variable if not yet set
  set_fact:
    miarka_deployment: "{{ miarka_deployment | default(false) }}"

- name: create folder for config
  file:
    path: "{{ checkqc_config_path | dirname }}"
    state: directory
    mode: "{{ omit if miarka_deployment  else '0775' }}"

###
# these next couple of tasks exist in order to preserve idempotence. If we modified the
# config file directly, ansible would restart checkQC every single time we run the role
###

- name: create temporary config file
  tempfile:
    state: file
  register: tmpconfig

- name: copy default config to temporary file
  copy:
    src: /tmp/checkQC/checkQC/default_config/config.yaml
    remote_src: yes
    dest: "{{ tmpconfig.path }}"
    mode: "{{ omit if miarka_deployment else '0664' }}"

- name: change bcl2fastq output path
  lineinfile:
    path: "{{ tmpconfig.path }}"
    regexp: '^([ \t]*bcl2fastq_output_path:)'
    line: '\1 {{ checkqc_bcl2fastq_output_path }}'
    backrefs: yes
    mode: "{{ omit if miarka_deployment else '0664' }}"

###
# end of idempotence-keeping
###

- name: deploy config file
  copy:
    src: "{{ tmpconfig.path }}"
    remote_src: yes
    dest: "{{ checkqc_config_path }}"
    backup: yes
    mode: "{{ omit if miarka_deployment else '0664' }}"

- name: remove temporarily checkqc repo
  file:
    path: /tmp/checkQC
    state: absent

