---

- name: Set host fact boolean for miarka deployment
  set_fact:
    on_miarka: "{{ env_current == env_prod or env_current == env_staging }}"

- name: install pip
  yum:
    name: python3-pip
    state: present

- name: install virtualenv
  pip:
    name: virtualenv

- import_tasks: seqreports_dev.yml
  when: not on_miarka

- name: ensure seqreports user owns data directory
  file:
    path: "{{ seqreports_data_path }}"
    state: directory
    owner: "{{ omit if on_miarka else seqreports_user }}"
    group: "{{ omit if on_miarka else seqreports_group }}"
    mode: "{{ omit if on_miarka else '0755' }}"

- name: Install unzip
  yum:
    name: unzip
    update_cache: yes
    state: present

# develop-1737, as far as I understand, no tasks in this file are needed on miarka. I have a note that "seqreports fastc screen db path" is already on a volume on irma/miarka
- import_tasks: pre_reqs.yml
  tags: seqreports_prereqs
  when: not on_miarka

- name: create conda environment for seqreports
  shell: "{{ miniconda_dest }}/bin/conda create -y -p {{ seqreports_env_path }} python=3.7"
  args:
    creates: "{{ seqreports_env_path }}/bin/python3"

- name: ensure nextflow directories exist and belong to seqreports user
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ omit if on_miarka else seqreports_user }}"
    group: "{{ omit if on_miarka else seqreports_group }}"
    mode: "{{ omit if on_miarka else '0755' }}"
  loop:
    - "{{ seqreports_nxf_temp }}"
    - "{{ seqreports_nxf_work }}"
    - "{{ seqreports_nxf_logs }}"

- name: Update and deploy checkQC config
  include_role:
    name: checkqc
    tasks_from: deploy_config.yml

