---

- name: create conda environment for seqreports
  shell: "{{ anaconda_path }}/bin/conda create -n {{ seqreports_venv_name }} -c anaconda python=3.8 -y"
  args:
    creates: "{{ anaconda_path }}/envs/{{ seqreports_venv_name }}/bin/python3"

- name: Set host fact boolean for miarka deployment
  set_fact:
    apply_to_conda: "{{ apply_to_conda | default(true) }}"

- name: ensure seqreports data path exists
  file:
    path: "{{ seqreports_data_path }}"
    state: directory

- name: ensure nextflow directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ seqreports_nxf_temp }}"
    - "{{ seqreports_nxf_work }}"
    - "{{ seqreports_nxf_logs }}"

- import_tasks: pre_reqs.yml

- import_tasks: seqreports_dev.yml
  when: not apply_to_conda | bool

- name: Update and deploy checkQC config
  include_role:
    name: checkqc
    tasks_from: deploy_config.yml

