---

# If this playbook was triggered from sysman, we download the fastq_screen_reference genomes 
# to the orchestration/local machine and then transfer them to the
# target machine, since this will be super slow to download, and we don't want to keep redoing it,
# especially when running locally.
- name: ensure directory exists locally (sysman), or at resources (miarka)
  file:
    # noqa 208
    # Adding lint exception since setting permissions on this folder is troublesome because it is done locally
    # and will be done by different users 
    state: directory
    path: "{{ seqreports_fastq_screen_resource_path }}"
  delegate_to: localhost

- name: download fastq_screen genomes (please note this will be very slow)
  command: python cmd/helpers/get_fastq_screen_reference_genomes.py {{ seqreports_fastq_screen_resource_path }}
  args:
    creates: "{{ seqreports_fastq_screen_resource_path }}/FastQ_Screen_Genomes"
  delegate_to: localhost
  # In the version of ansible-lint (3.5.1) that we are currently using
  # there is a bug, which crashes ansible-lint if arv is used as above.
  # https://github.com/ansible/ansible-lint/issues/352
  # Therefore we will skip linting of this task for now.
  # /JD 2018-03-27
  tags:
    - skip_ansible_lint

- name: ensure genomes working dir exists
  file:
    path: "{{ seqreports_data_fastq_screen_db_path }}"
    state: directory
    owner: "{{ seqreports_user }}"
    mode: "0555"
  when: not apply_to_conda | bool

- name: synchronize genomes to host
  synchronize:
    src: "{{ seqreports_fastq_screen_resource_path }}/FastQ_Screen_Genomes/"
    dest: "{{ seqreports_data_fastq_screen_db_path }}"
    recursive: yes
  when: not apply_to_conda | bool

- name: ensure genomes are readable to user after upload
  file:
    path: "{{ seqreports_data_fastq_screen_db_path }}"
    owner: "{{ seqreports_user }}"
    mode: "0555"
    recurse: yes
  when: not apply_to_conda | bool

- name: Create symlink to FastQ_Screen_Genomes (miarka only)
  file:
    src: "{{ seqreports_fastq_screen_resource_path }}/FastQ_Screen_Genomes"
    dest: "{{ seqreports_data_fastq_screen_db_path }}"
    state: link
  when: apply_to_conda | bool

