
- set_fact:
    biocontainer_filename: "nf-core-{{ pipeline }}_v{{ release }}"

- name: check if biocontainers exists
  stat:
    get_attributes: no
    get_checksum: no
    get_mime: no
    path: "{{ ngi_containers }}/biocontainers/{{ biocontainer_filename }}"
  register: target_stat

- name: download biocontainers
  block:
    - name: create directory for biocontainers
      file:
        path: "{{ ngi_containers }}/biocontainers"
        state: directory
        mode: 02775 #ug=rwx, o=rx, g+s

    - name: Create temp directories for download
      file:
        path: "{{ ngi_containers }}/biocontainers/download"
        state: directory

    - name: download containers
      get_url:
        url: "{{ biocontainer_base_url }}/{{ biocontainer_filename }}.tar.gz"
        dest: "{{ ngi_containers }}/biocontainers/download/{{ biocontainer_filename }}.tar.gz"

    - name: Unarchive downloaded file
      unarchive:
        src: "{{ ngi_containers }}/biocontainers/download/{{ biocontainer_filename }}.tar.gz"
        dest: "{{ ngi_containers }}/biocontainers/"
        remote_src: yes

    - name: Find all unarchived files
      find:
        paths: "{{ ngi_containers }}/biocontainers/{{ biocontainer_filename }}"
      register: find

    - name: Create symlinks to images
      file:
        src: "{{ pth.path }}"
        dest: "{{ ngi_containers }}/biocontainers/{{ pth.path | basename }}"
        state: link
      with_items: "{{ find.files }}"
      loop_control:
        loop_var: pth

    - name: Clean download
      file:
        path: "{{ ngi_containers }}/biocontainers/download"
        state: absent

  when: not target_stat.stat.exists
