
- name: Create recalibration script and add to TACA resources
  template:
    src: "apply_recalibration.sh.j2"
    dest: "{{ ngi_resources }}/TACA/apply_recalibration.sh"

- name: Create Delivery READMEs and add to TACA resources
  template:
    src: "DELIVERY.README.SAREK.txt.j2"
    dest: "{{ ngi_resources }}/TACA/{{ site }}/DELIVERY.README.SAREK.txt"

- name: Create Delivery READMEs for WES and add to TACA resources
  template:
    src: "DELIVERY.README.SAREK.WES.md.j2"
    dest: "{{ ngi_resources }}/TACA/{{ site }}/DELIVERY.README.SAREK.WES.md"
  when: site == "upps"
