---
taca_ngi_repo: https://github.com/SciLifeLab/taca-ngi-pipeline.git
taca_ngi_dest: "{{ sw_path }}/taca-ngi-pipeline"
taca_ngi_version: 139aa22e6373f7dc3d54d472a6f7ca9f2c5371bc

flowcell_parser_repo: https://github.com/SciLifeLab/flowcell_parser.git
flowcell_parser_dest: "{{ sw_path }}/flowcell_parser"
flowcell_parser_version: 4ec4331bf6f968bb4a83b00c9c111d87823049de

taca_repo: https://github.com/SciLifeLab/TACA.git
taca_dest: "{{ sw_path }}/TACA"
taca_version: 1be99be549543f208cb654db1fe9d157edf57b05
