
- name: ensure {{ arteria_service_name }} conf dir exists
  file:
    state: directory
    path: "{{ arteria_service_config_root }}"

- name: deploying {{ arteria_service_name }} app config
  template:
    src: delivery_app.config.j2 # TODO replace with seqreport templates
    dest: "{{ arteria_service_config_root }}/app.config"

- name: deploying {{ arteria_service_name }} logger config
  template:
    src: delivery_logger.config.j2
    dest: "{{ arteria_service_config_root }}/logger.config"

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:{{ arteria_service_name }}-{{ deployment_environment }}
    option: command
    value: "{{ arteria_service_env_root }}/bin/sequencing-report-service --configroot={{ arteria_service_config_root }} --port={{ seqreport_service_port }}"
    backup: no

- name: modify uppsala's supervisord conf to autostart {{ arteria_service_name }}
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:{{ arteria_service_name }}-{{ deployment_environment }}
    option: autorestart
    value: true
    backup: no
