---

- name: create virtual python env for arteria-checksum
  shell: "conda create --name {{ arteria_service_name }} python=2.7"
  args:
    creates: "{{ arteria_service_env_root }}"

- name: make sure pip is up to date
  shell: "{{ arteria_service_env_root }}/bin/python -m ensurepip --upgrade"

- name: get arteria-checksum from git
  git:
    repo: "{{ arteria_checksum_repo }}"
    dest: "{{ arteria_service_src_path }}"
    version: "{{ arteria_checksum_version }}"

- name: install arteria-checksum requirements
  pip:
    requirements: "{{ arteria_service_src_path }}/requirements/prod"
    chdir: "{{ arteria_service_src_path }}"
    executable: "{{ arteria_service_env_root }}/bin/pip"
    state: present

- name: install arteria-checksum
  pip:
    name: .
    chdir: "{{ arteria_service_src_path }}"
    executable: "{{ arteria_service_env_root }}/bin/pip"
    state: present
