---

# If deploying to staging one should call with
# -e deployment_environment=staging
# One can also override the default installed version
# by overriding the arteria_checksum_version on the command line.
#
# This will set corresponding paths and use the appropriate port.
arteria_checksum_repo: https://github.com/arteria-project/arteria-checksum.git
arteria_checksum_version: v1.0.4

# These values will be appended with production and staging specific
# paths in the tasks.
#
# NB. The log dirs need to be created manually on destination cluster.
#
# NB 2. Hard coded root path for runfolders, because that path
# needs to be reachable from outside world; i.e. have to be under /proj.
# And hard coded log paths because we do not want the log files
# to disappear when the wildwest directory is cleaned out with every
# staging sync.
arteria_service_name: arteria-checksum-ws
arteria_checksum_md5sum_log_dir: "{{ arteria_service_log_dir }}"
arteria_checksum_service_log: "{{ arteria_service_log_dir }}/{{ arteria_service_name }}.log"
arteria_checksum_cores_to_use: 8
