nf_core_env_name: nf-core-env
nf_core_env: "{{ sw_path }}/anaconda/envs/{{ nf_core_env_name }}"
nf_core_version: 2.1
nf_core_container_repo: docker://nfcore
nf_core_vars:
  NFCORE_NO_VERSION_CHECK: 1
  SINGULARITY_CACHEDIR: /scratch/{{ deployment_version }}/singularity_cache
  SINGULARITY_TMPDIR: /scratch/{{ deployment_version }}/singularity_temp
  NXF_SINGULARITY_CACHEDIR: "{{ container_dir }}"
  NXF_SINGULARITY_LIBRARY: "{{ container_dir }}"
  NXF_LAUNCHER: "{{ nextflow_env.NXF_LAUNCHER }}"
  NXF_HOME: "{{ nextflow_env.NXF_HOME }}"
  NXF_WORK: "{{ nextflow_env.NXF_WORK }}"
  NXF_TEMP: "{{ nextflow_env.NXF_TEMP }}"
  NXF_VER: "{{ nextflow_env.NXF_VER }}"
  JAVA_HOME: "{{ nextflow_env.NXF_JAVA_HOME }}"
  PATH: "{{ nf_core_env }}/bin:{{ tools_path.PATH }}"
biocontainers_dirname: biocontainers
pipelines:
  - name: rnaseq
    release: 3.3
    container_dir: "{{ biocontainers_dirname }}"
    biocontainer_base_url: https://dl.dropboxusercontent.com/s/5venz3l2wihaqdp
  - name: sarek
    release: "{{ sarek_tag }}"
    pipeline_specific_containers:
      - sarekvep
      - sareksnpeff
    pipeline_genomes:
      - GRCh38
      - GRCh37
      - GRCm38
      - CanFam3.1
  - name: methylseq
    release: 1.6.1
  - name: ampliseq
    release: 2.0.0
    silva_base_url: https://www.arb-silva.de/fileadmin/silva_databases/qiime
    silva_zip: Silva_132_release.zip
    container_dir: "{{ biocontainers_dirname }}"
  - name: atacseq
    release: 1.2.1
  - name: viralrecon
    release: 2.2
    container_dir: "{{ biocontainers_dirname }}"
  - name: rnafusion
    release: 1.2.0
  - name: nanoseq
    release: 1.1.0
