java_home: /sw/comp/java/x86_64/OracleJDK_11.0.9
nextflow_java: "{{ java_home }}"
nextflow_version_tag: 24.04.1
nextflow_download_url: https://github.com/nextflow-io/nextflow/releases/download/v{{ nextflow_version_tag }}/nextflow
nextflow_local_env:
  NXF_HOME: "{{ nextflow_dest }}/workfiles"
  NXF_OPTS: -Xms1g -Xmx3500m
  NXF_JAVA_HOME: "{{ nextflow_java }}"
  NXF_PLUGINS_DIR: "{{ nextflow_dest }}/workfiles/plugins"
  PATH: "{{ tools_path.PATH }}"
nextflow_env:
  NXF_HOME: "{{ nextflow_dest }}/workfiles"
  NXF_LAUNCHER: "$PWD/work"
  NXF_TEMP: "{{ ngi_pipeline_nobackup }}/nextflow/temp"
  NXF_WORK: "{{ ngi_pipeline_nobackup }}/nextflow/work"
  NXF_OPTS: -Xms1g -Xmx3500m
  NXF_JAVA_HOME: "{{ nextflow_java }}"
  NXF_PLUGINS_DIR: "{{ nextflow_dest }}/workfiles/plugins"
  NXF_SINGULARITY_HOME_MOUNT: true
  PATH: "{{ tools_path.PATH }}"
nextflow_plugins:
  - name: nf-validation
    version: 1.1.2
  - name: nf-prov
    version: 1.2.1
  - name: nf-tower
    version: 1.6.3
