---

- block:
  - include: install.yml
  - include: install_config.yml

  - name: add static folders to be created
    set_fact:
      static_folders: "{{ static_folders + [arteria_service_log_dir, runfolder_path] }}"

  - name: Store {{ arteria_service_name }} tool version in deployment
    lineinfile:
      dest: "{{ deployed_tool_versions }}"
      line: "{{ arteria_service_name }}: {{ seqreport_service_version }}"
  when: site in ["upps"]
