---

- name: ensure {{ arteria_service_name }} conf dir exists
  file:
    state: directory
    path: "{{ arteria_service_config_root }}"

- name: deploying {{ arteria_service_name }} app config
  copy:
    src: checkqc.config
    dest: "{{ arteria_service_config_root }}/app.config"

- name: deploy {{ arteria_service_name }} logger config
  template:
    src: checkqc_logger.config.j2
    dest: "{{ arteria_service_config_root }}/logger.config"

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:{{ arteria_service_name }}-{{ deployment_environment }}
    option: command
    value: >
      {{ arteria_service_env_root }}/bin/checkqc-ws
      --config {{ arteria_service_config_root }}/app.config
      --log_config {{ arteria_service_config_root }}/logger.config
      --port={{ checkqc_service_port }}
      {{ static_runfolder_path }}
    backup: no

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: "program:{{ arteria_service_name }}-{{ deployment_environment }}"
    option: autorestart
    value: true
    backup: no
