---

- name: Create ngi_pipeline staging incoming & archive directories for {{ site }}
  file: path="{{ proj_root }}/{{ item.delivery }}/{{ item.dir }}" state=directory mode=g+s
  with_items:
    - { delivery: "{{ ngi_pipeline_delivery }}", dir: "incoming"}
    - { delivery: "{{ ngi_pipeline_delivery }}", dir: "archive"}
  when: deployment_environment in ["staging", "devel"]

- name: Deploy irma ngi_pipeline config for {{ site }}
  template: src="irma_ngi_config.yaml.j2" dest="{{ ngi_pipeline_conf }}/{{ site_config }}"

- name: Deploy bash environment variables for {{ site }}
  template: src="{{ bash_env_site_script }}" dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"

- name: Add py3 anaconda env path to sourceme script for {{ site }}
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line='export PATH={{ anaconda_path }}/envs/{{ NGI_venv_py3_name }}/bin:$PATH'
              backup=no
  when: site == "sthlm"
