---

- name: create {{ arteria_service_name }} folders
  file: path="{{ item }}"
        state=directory
        mode=g+rwXs
  with_items:
    - "{{ arteria_service_src_path }}"
    - "{{ arteria_service_src_path }}/bin"

- name: add {{ arteria_service_name }} bin folder to Uppsala path
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line='export PATH={{ arteria_service_src_path }}/bin:$PATH'
              backup=no

- name: deploy start and stop scripts for {{ arteria_service_name }}
  template:
    src: "{{ item }}.j2"
    dest: "{{ arteria_service_src_path }}/bin/{{ item }}"
    mode: "u=rwx,g=rwx"
  with_items:
    - "start-arteria-staging"
    - "stop-arteria-staging"

- name: deploy {{ arteria_service_name }} screen script
  template:
    src: arteria-staging.screen.j2
    dest: "{{ arteria_service_src_path }}/{{ arteria_service_name }}.screen"
