- include: dependencies.yml

- name: Fetch TACA-ngi-pipeline from GitHub
  git: repo="{{ taca_ngi_repo }}"
       dest="{{ taca_ngi_dest }}"
       version="{{ taca_ngi_version }}"
       force=yes

- name: Install TACA-ngi-pipeline requirements
  pip:
    requirements: "{{ taca_ngi_dest }}/requirements.txt"
    executable: "{{ ngi_pipeline_venv }}/bin/pip"

- name: Install TACA-ngi-pipeline
  pip:
    name: "file:{{ taca_ngi_dest }}"
    executable: "{{ ngi_pipeline_venv }}/bin/pip"

- name: Create TACA delivery configs directory
  file: path="{{ ngi_pipeline_conf }}/TACA" state=directory mode=g+s

- name: Create TACA resources folders for each site
  file:
    path: "{{ ngi_resources }}/TACA/{{ item }}"
    state: directory
    mode: g+s
  with_items:
    - "upps"
    - "sthlm"

- set_fact:
    site: "upps"
    site_full: "uppsala"
    ngi_pipeline_site_path: "{{ ngi_pipeline_upps_path }}"
    ngi_site_softlinks: "{{ ngi_upps_softlinks }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_upps_delivery }}"
    recipient_mail: "{{ recipient_mail_upps }}"

- name: Deploy {{ site }} TACA site configs
  template: src="site_{{ item.config_tpl }}.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.config_dst }}.yml"
  with_items:
    - { config_tpl: "taca_delivery", config_dst: "taca_delivery" }
    - { config_tpl: "taca_sarek_delivery", config_dst: "taca_sarek_delivery" }

- set_fact:
    site: "sthlm"
    site_full: "stockholm"
    ngi_pipeline_site_path: "{{ ngi_pipeline_sthlm_path }}"
    ngi_site_softlinks: "{{ ngi_sthlm_softlinks }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_sthlm_delivery }}"
    recipient_mail: "{{ recipient_mail_sthlm }}"

- name: Deploy {{ site }} TACA site configs
  template: src="site_{{ item.config_tpl }}.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.config_dst }}.yml"
  with_items:
    - { config_tpl: "taca_cleanup", config_dst: "taca_cleanup" }
    - { config_tpl: "fastq_delivery", config_dst: "taca_fastq_delivery" }
    - { config_tpl: "taca_delivery", config_dst: "taca_wgs_delivery" }
    - { config_tpl: "taca_sarek_delivery", config_dst: "taca_sarek_delivery" }
    - { config_tpl: "taca_runfolder_delivery", config_dst: "taca_runfolder_delivery" }
    - { config_tpl: "app_specific_delivery", config_dst: "taca_rna_delivery" }
    - { config_tpl: "app_specific_delivery", config_dst: "taca_denovo_delivery" }


- name: Deploy script for softlinking sthlm delivery Readmes
  template: src="create_delivery_readme_softlinks.sh.j2" dest="{{ ngi_resources }}/create_delivery_readme_softlinks.sh"

- name: Store taca tools version on deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "{{ item.tool_name }}: {{ item.tool_version }}"
  with_items:
    - { tool_name: "TACA", tool_version: "{{ taca_version }}" }
    - { tool_name: "taca-ngi-pipeline", tool_version: "{{ taca_ngi_version }}" }
    - { tool_name: "StatusDB", tool_version: "{{ statusdb_version }}" }
    - { tool_name: "flowcell_parser", tool_version: "{{ flowcell_parser_version }}" }
