---

- name: download miniconda
  get_url:
    url: "{{ miniconda_url }}"
    dest: "{{ miniconda_src }}"

- name: set miniconda src premissions
  file:
    path: "{{ miniconda_src }}"
    mode: "0770"
  ignore_errors: "{{ ansible_check_mode }}"

- name: install miniconda
  shell: "{{ miniconda_src }} -b -p {{ anaconda_path }}"
  args:
    creates: "{{ anaconda_path }}/LICENSE.txt"
  tags: skip_ansible_lint
  ignore_errors: "{{ ansible_check_mode }}"

